name: "RFID App Tag"
on:
  push:
    tags:
      - v*.*
jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: "PHP 8.3"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-'8.2'-composer-${{ hashFiles('composer.json') }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Setup for deploy
        run: make deploy-setup

      - name: "Install SSH key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: "Deploy"
        run: make deploy

