name: "isconklive CICD"
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
    name: PHP ${{ matrix.php }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Cache dependencies"
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: "Setup Env"
        run: cp .env.example .env

      - name: "Install dependencies & Setup App"
        run: make cicd-setup

      - name: "Run Tests & PhpStan"
        run: make test

#      - name: "Install SSH key"
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_KEY }}
#          known_hosts: ${{ secrets.KNOWN_HOSTS }}
#        if: github.ref == 'refs/heads/master'
#
#      - name: "Deploy"
#        run: make deploy
#        if: github.ref == 'refs/heads/master'
